# Getting Started with pandas

In [ ]:
%pip install pandas

Requirement already satisfied: pandas in ./.venv/lib/python3.13/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in ./.venv/lib/python3.13/site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import numpy as np
import pandas as pd

In [4]:
from pandas import Series, DataFrame

In [19]:
obj = pd.Series([4, 7, -5, 3])

### Series

Series are very similar to dictionaries, but if you do not put any index (or label, or keys) then it is indexed conventionally

In [20]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [7]:
obj.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [8]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])

In [10]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [11]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='str')

You can use the index to do the slicing, but beware that the standard notation is subtle, because pandas tries to interpret whether you are trying to use indices, positions or booleans.

In [12]:
obj2["a"]

np.int64(-5)

In [19]:
obj2.iloc[1:3]

b    7
a   -5
dtype: int64

In [21]:
obj2.loc[["a", "d"]]

a   -5
d    4
dtype: int64

In [22]:
obj2.loc[["d", "a"]]

d    4
a   -5
dtype: int64

You can do some pretty fancy slicing, and all the things that you were doing on arrays in NumPy, but here the indices are kept linked to the values even after the operations

In [23]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [24]:
obj2*3

d    12
b    21
a   -15
c     9
dtype: int64

In [25]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [26]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [27]:
"e" in obj2

False

Should you have data contained in a Python dictionary, you can create a Series from it by passing the dictionary:

In [6]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

In [29]:
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [12]:
obj3 = pd.Series(sdata)

In [14]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [32]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

When you are only passing a dictionary, the index in the resulting Series will respect the order of the keys according to the dictionary’s keys method, which depends on the key insertion order. You can override this by passing an index with the dictionary keys in the order you want them to appear in the resulting Series:

In [1]:
states = ["California", "Ohio", "Oregon", "Texas"]

In [7]:
obj4 = pd.Series(sdata, index=states)

Since California was passed as an index but was not in the dictionary that we wanted to convert it has been assigned NaN. Conversely, Utah did not appear in the list of indices and so it does not appear in the Series

In [8]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [9]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [10]:
obj4.notna()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

A useful Series feature for many applications is that it automatically aligns by index label in arithmetic operations:

In [13]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

Both the Series object itself and its index have a name attribute, which integrates with other areas of pandas functionality:

In [15]:
obj4.name = "population"

In [16]:
obj4.index.name = "state"

In [17]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [21]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [22]:
obj.index=["Mario", "Giovanni", "Luca", "Enrico"]

In [23]:
obj

Mario       4
Giovanni    7
Luca       -5
Enrico      3
dtype: int64

In [ ]:
obj

### DataFrame

A DataFrame represents a rectangular table of data and contains an ordered, named collection of columns, each of which can be a different value type (numeric, string, Boolean, etc.). The DataFrame has both a row and column index; it can be thought of as a dictionary of Series all sharing the same index. There are many ways to construct a DataFrame, though one of the most common is from a dictionary of equal-length lists or NumPy arrays:

In [24]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],  "year": [2000, 2001, 2002, 2001, 2002, 2003], "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]} 
frame = pd.DataFrame(data)

In [25]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [26]:
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [27]:
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [28]:
pd.DataFrame(data, columns=["year", "state", "pop"])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [29]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])

In [30]:
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [31]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='str')

In [32]:
frame["year"]

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [33]:
frame.state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: str

In [39]:
val = pd.Series([-1.2, -1.5, -1.7], index=["Ohio", "h", "m"])

In [40]:
frame2["debt"] = val

In [41]:
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [42]:
frame2["oil"]=val

In [43]:
frame2

   year   state  pop  debt  oil
0  2000    Ohio  1.5   NaN  NaN
1  2001    Ohio  1.7   NaN  NaN
2  2002    Ohio  3.6   NaN  NaN
3  2001  Nevada  2.4   NaN  NaN
4  2002  Nevada  2.9   NaN  NaN
5  2003  Nevada  3.2   NaN  NaN

In [50]:
frame2["eastern"]=frame2["state"]=="Ohio"

In [51]:
frame2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

In [54]:
del frame2["eastern"]

In [55]:
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [49]:
del frame2["oil"]

In [57]:
frame2.index

RangeIndex(start=0, stop=6, step=1)

In [58]:
obj

Mario       4
Giovanni    7
Luca       -5
Enrico      3
dtype: int64

In [59]:
obj.index

Index(['Mario', 'Giovanni', 'Luca', 'Enrico'], dtype='str')

In [62]:
obj.index[0:3]

Index(['Mario', 'Giovanni', 'Luca'], dtype='str')

Immutability makes it safer to share Index objects among data structures.

In [64]:
obj

Mario       4
Giovanni    7
Luca       -5
Enrico      3
dtype: int64

In [65]:
obj.index.name="Names"

In [74]:
obj=DataFrame(obj)

In [75]:
obj

          0
Names
Mario     4
Giovanni  7
Luca     -5
Enrico    3

In [81]:
obj[0].name="Money"

In [82]:
obj

          0
Names
Mario     4
Giovanni  7
Luca     -5
Enrico    3

In [83]:
obj.index

Index(['Mario', 'Giovanni', 'Luca', 'Enrico'], dtype='str', name='Names')

In [89]:
obj

          Money
Names
Mario         4
Giovanni      7
Luca         -5
Enrico        3

In [91]:
obj["Luck"]=[0,2,3,4]

In [92]:
obj

          Money  Luck
Names
Mario         4     0
Giovanni      7     2
Luca         -5     3
Enrico        3     4

In [94]:
obj["car"]=np.arange(4)

In [95]:
obj

          Money  Luck  car
Names
Mario         4     0    0
Giovanni      7     2    1
Luca         -5     3    2
Enrico        3     4    3

In [100]:
obj["car"]

Names
Mario       0
Giovanni    1
Luca        2
Enrico      3
Name: car, dtype: int64

In [105]:
obj.rename(columns={"car":"Car"}, inplace=True)

In [106]:
obj

          Money  Luck  Car
Names
Mario         4     0    0
Giovanni      7     2    1
Luca         -5     3    2
Enrico        3     4    3

In [107]:
obj.columns.name="Attributes"

In [108]:
obj

Attributes  Money  Luck  Car
Names
Mario           4     0    0
Giovanni        7     2    1
Luca           -5     3    2
Enrico          3     4    3

In [116]:
obj.loc[len(obj)]={"Money": -3, "Luck":0, "Car":4}

In [117]:
obj

Attributes  Money  Luck  Car
Names
Mario         4.0   0.0  0.0
Giovanni      7.0   2.0  1.0
Luca         -5.0   3.0  2.0
Enrico        3.0   4.0  3.0
4             NaN   NaN  NaN
5            -3.0   0.0  4.0

In [140]:
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [141]:
frame2.rename(index={0:"blabla"})

        year   state  pop  debt
blabla  2000    Ohio  1.5   NaN
1       2001    Ohio  1.7   NaN
2       2002    Ohio  3.6   NaN
3       2001  Nevada  2.4   NaN
4       2002  Nevada  2.9   NaN
5       2003  Nevada  3.2   NaN

In [142]:
frame2.rename(columns={"state":"dudu"})

   year    dudu  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [144]:
frame2.name="dada"

In [146]:
frame2.name

'dada'

In [149]:
frame2.columns.name="data"

In [150]:
frame2

data  year   state  pop  debt
0     2000    Ohio  1.5   NaN
1     2001    Ohio  1.7   NaN
2     2002    Ohio  3.6   NaN
3     2001  Nevada  2.4   NaN
4     2002  Nevada  2.9   NaN
5     2003  Nevada  3.2   NaN

In [152]:
frame2.index.name="time"

In [153]:
frame2

data  year   state  pop  debt
time
0     2000    Ohio  1.5   NaN
1     2001    Ohio  1.7   NaN
2     2002    Ohio  3.6   NaN
3     2001  Nevada  2.4   NaN
4     2002  Nevada  2.9   NaN
5     2003  Nevada  3.2   NaN

## 5.2 Essential Functionality

We’ll focus on familiarizing you with heavily used features, leaving the less common (i.e., more esoteric) things for you to learn more about by reading the online pandas documentation

### Reindexing

In [154]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])

In [155]:
obj2=obj.reindex(["a","b","c","d","e"])

In [156]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

You may want to do some interpolation or filling of values when reindexing. The method option allows us to do this, using a method such as `ffill`, which forward-fills **the values**:

In [157]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])

In [158]:
obj3

0      blue
2    purple
4    yellow
dtype: str

In [164]:
obj4=obj3.reindex(index=np.arange(6), method="ffill")

### Dropping entries from an Axis

In [165]:
obj4.drop(0)

1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: str

With DataFrame, index values can be deleted from either axis

In [166]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=["Ohio", "Colorado", "Utah", "New York"], columns=["one", "two", "three", "four"])

In [167]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [168]:
data.drop(index=["Colorado", "Ohio"])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [169]:
data.drop(columns=["two"])

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

### Indexing, Selection, Filtering

You can either use the index or the position to extract a value from a series, but the position is ambiguous and not recommended (when using a single position it throws an error sometimes and it is better to use the `iloc` method)

In [170]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [171]:
obj["b"]

np.float64(1.0)

In [172]:
obj[1:3]

b    1.0
c    2.0
dtype: float64

In [174]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=["Ohio", "Colorado", "Utah", "New York"], columns=["one", "two", "three", "four"])

In [175]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [180]:
data["one"]

Ohio         0
Colorado     4
Utah         8
New York    12
Name: one, dtype: int64

In [176]:
data[["three", "one"]]

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [177]:
data[data["three"]>5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [181]:
data<5

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [182]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [185]:
data.loc["Colorado"]

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [186]:
data.loc[["Colorado", "New York"]]

          one  two  three  four
Colorado    4    5      6     7
New York   12   13     14    15

In [187]:
data.loc["Colorado", ["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

### Arithmetic and Data Alignment

pandas can make it much simpler to work with objects that have different indexes. For example, when you add objects, if any index pairs are not the same, the respective index in the result will be the union of the index pairs

In [188]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=["a", "c", "e", "f", "g"])

In [190]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In the case of DataFrame, alignment is performed on both rows and columns:

In [191]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"), index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"), index=["Utah", "Ohio", "Texas", "Oregon"])

In [192]:
df1

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [193]:
df2

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [194]:
df1+df2

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [195]:
df1.index

Index(['Ohio', 'Texas', 'Colorado'], dtype='str')

In [196]:
df1.reindex(["Texas", "Ohio", "Colorado"])

            b    c    d
Texas     3.0  4.0  5.0
Ohio      0.0  1.0  2.0
Colorado  6.0  7.0  8.0

In [197]:
df1+df2

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

If you add DataFrame objects with no column or row labels in common, the result will contain all nulls. In arithmetic operations between differently indexed objects, you might want to fill with a special value, like 0, when an axis label is found in one object but not the other.

In [198]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list("abcd"))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list("abcde"))

In [200]:
df1+df2

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [199]:
df1.add(df2, fill_value=0)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [201]:
df1.add(df2, fill_value=1000)

        a       b       c       d       e
0     0.0     2.0     4.0     6.0  1004.0
1     9.0    11.0    13.0    15.0  1009.0
2    18.0    20.0    22.0    24.0  1014.0
3  1015.0  1016.0  1017.0  1018.0  1019.0

When reindexing a Series or DataFrame, you can also specify a different fill value:

In [202]:
df1.reindex(columns=df2.columns, fill_value=0)

     a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

Arithmetic between DataFrame and Series is also defined. Let us consider an example using arrays

In [203]:
arr = np.arange(12.).reshape((3, 4))

In [204]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

This is an example of **broadcasting**. By default, arithmetic between DataFrame and Series matches the index of the Series on the columns of the DataFrame, broadcasting down the rows:

In [205]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"), index=["Utah", "Ohio", "Texas", "Oregon"])

In [206]:
series = frame.iloc[0]

In [207]:
frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [208]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [209]:
frame-series

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [210]:
series2 = pd.Series(np.arange(3), index=["b", "e", "f"])

In [211]:
frame+series2

          b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

If you want to instead broadcast over the columns, matching on the rows, you have to use one of the arithmetic methods and specify to match over the index.

In [212]:
series3 = frame["d"]

In [214]:
frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [215]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [213]:
frame.sub(series3, axis="index")

          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Function Application and Mapping

In [216]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)), columns=list("bde"), index=["Utah", "Ohio", "Texas", "Oregon"])

In [217]:
frame

               b         d         e
Utah   -0.746503  0.923082  0.659939
Ohio   -0.366698 -0.210139 -0.373486
Texas  -1.243308  1.399762 -1.256766
Oregon -0.427633 -0.901961 -1.405265

In [218]:
np.abs(frame)

               b         d         e
Utah    0.746503  0.923082  0.659939
Ohio    0.366698  0.210139  0.373486
Texas   1.243308  1.399762  1.256766
Oregon  0.427633  0.901961  1.405265

Another frequent operation is applying a function on one-dimensional arrays to each column or row. DataFrame’s apply method does exactly this:

In [219]:
def f1(x): 
    return x.max() - x.min()

In [220]:
frame.apply(f1)

b    0.876610
d    2.301723
e    2.065204
dtype: float64

If you pass `axis="columns"` to apply, the function will be invoked once per row instead.

In [221]:
frame.apply(f1, axis="columns")

Utah      1.669585
Ohio      0.163347
Texas     2.656528
Oregon    0.977633
dtype: float64

The function passed to apply need not return a scalar value; it can also return a Series with multiple values:

In [222]:
def f2(x): 
    return pd.Series([x.min(), x.max()], index=["min", "max"])

In [223]:
frame.apply(f2)

            b         d         e
min -1.243308 -0.901961 -1.405265
max -0.366698  1.399762  0.659939

In [224]:
def my_format(x): 
    return f"{x:.2f}"

In [230]:
fr2=frame.map(my_format)

In [231]:
fr2["e"].dtype

### Sorting and Ranking

In [232]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])

In [233]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [241]:
obj.sort_values()

d    0
a    1
b    2
c    3
dtype: int64

In [234]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), index=["three", "one"], columns=["d", "a", "b", "c"])

In [236]:
frame

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [235]:
frame.sort_index()

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [239]:
frame.sort_index(axis="columns", ascending=True) #default ascending=True

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

Any missing values are sorted to the end of the Series by default

In [242]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [243]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [244]:
obj.sort_values(na_position="first")

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

When sorting a DataFrame, you can use the data in one or more columns as the sort keys. To do so, pass one or more column names to sort_values:

In [245]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})

In [246]:
frame

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [247]:
frame.sort_values("b")

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [252]:
frame.sort_values(["a","b"])

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

**Ranking** assigns ranks from one through the number of valid data points in an array,  starting from the lowest value. The rank methods for Series and DataFrame are the place to look; by default, rank breaks ties by assigning each group the mean rank:

In [259]:
obj = pd.Series([7, -5, 7, 4, 1000, 0, 4,-1])

In [260]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    8.0
5    3.0
6    4.5
7    2.0
dtype: float64

In [261]:
obj.rank(method="first")

0    6.0
1    1.0
2    7.0
3    4.0
4    8.0
5    3.0
6    5.0
7    2.0
dtype: float64

In [262]:
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1], "c": [-2, 5, 8, -2.5]})

In [263]:
frame

     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [264]:
frame.rank(axis="columns")

     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### Axis Indexes with Duplicate Labels

In [265]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])

In [266]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [267]:
obj.index.is_unique

False

In [268]:
obj["a"]

a    0
a    1
dtype: int64

The same logic extends to indexing rows (or columns) in a DataFrame

In [269]:
df = pd.DataFrame(np.random.standard_normal((5, 3)), index=["a", "a", "b", "b", "c"])

In [270]:
df

          0         1         2
a  1.646532  1.144130  1.936501
a  0.084949  0.109995 -0.209127
b -0.167368  0.101746 -0.002463
b  0.755811  0.120844 -0.330599
c -1.162865  0.336094  0.276625

In [271]:
df.loc["b"]

          0         1         2
b -0.167368  0.101746 -0.002463
b  0.755811  0.120844 -0.330599

In [272]:
df.loc["c"]

0   -1.162865
1    0.336094
2    0.276625
Name: c, dtype: float64