# 5 Getting Started with pandas

In [ ]:
%pip install pandas

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from pandas import Series, DataFrame

In [ ]:
obj = pd.Series([4, 7, -5, 3])

### Series

Series are very similar to dictionaries, but if you do not put any index (or label, or keys) then it is indexed conventionally

In [ ]:
obj

In [ ]:
obj.array

In [ ]:
obj.index

In [ ]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])

In [ ]:
obj2

In [ ]:
obj2.index

You can use the index to do the slicing, but beware that the standard notation is subtle, because pandas tries to interpret whether you are trying to use indices, positions or booleans.

In [ ]:
obj2["a"]

In [ ]:
obj2.iloc[1:3]

In [ ]:
obj2.loc[["a", "d"]]

In [ ]:
obj2.loc[["d", "a"]]

You can do some pretty fancy slicing, and all the things that you were doing on arrays in NumPy, but here the indices are kept linked to the values even after the operations

In [ ]:
obj2[obj2>0]

In [ ]:
obj2*3

In [ ]:
np.exp(obj2)

In [ ]:
obj2

In [ ]:
"e" in obj2

Should you have data contained in a Python dictionary, you can create a Series from it by passing the dictionary:

In [ ]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

In [ ]:
sdata

In [ ]:
obj3 = pd.Series(sdata)

In [ ]:
obj3

In [ ]:
obj3.to_dict()

When you are only passing a dictionary, the index in the resulting Series will respect the order of the keys according to the dictionary’s keys method, which depends on the key insertion order. You can override this by passing an index with the dictionary keys in the order you want them to appear in the resulting Series:

In [ ]:
states = ["California", "Ohio", "Oregon", "Texas"]

In [ ]:
obj4 = pd.Series(sdata, index=states)

Since California was passed as an index but was not in the dictionary that we wanted to convert it has been assigned NaN. Conversely, Utah did not appear in the list of indices and so it does not appear in the Series

In [ ]:
obj4

In [ ]:
obj4.isna()

In [ ]:
obj4.notna()

A useful Series feature for many applications is that it automatically aligns by index label in arithmetic operations:

In [ ]:
obj3+obj4

Both the Series object itself and its index have a name attribute, which integrates with other areas of pandas functionality:

In [ ]:
obj4.name = "population"

In [ ]:
obj4.index.name = "state"

In [ ]:
obj4

In [ ]:
obj

In [ ]:
obj.index=["Mario", "Giovanni", "Luca", "Enrico"]

In [ ]:
obj

In [ ]:
obj

### DataFrame

A DataFrame represents a rectangular table of data and contains an ordered, named collection of columns, each of which can be a different value type (numeric, string, Boolean, etc.). The DataFrame has both a row and column index; it can be thought of as a dictionary of Series all sharing the same index. There are many ways to construct a DataFrame, though one of the most common is from a dictionary of equal-length lists or NumPy arrays:

In [ ]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],  "year": [2000, 2001, 2002, 2001, 2002, 2003], "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]} 
frame = pd.DataFrame(data)

In [ ]:
frame

In [ ]:
frame.head()

In [ ]:
frame.tail()

In [ ]:
pd.DataFrame(data, columns=["year", "state", "pop"])

In [ ]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])

In [ ]:
frame2

In [ ]:
frame2.columns

In [ ]:
frame["year"]

In [ ]:
frame.state

In [ ]:
val = pd.Series([-1.2, -1.5, -1.7], index=["Ohio", "h", "m"])

In [ ]:
frame2["debt"] = val

In [ ]:
frame2

In [ ]:
frame2["oil"]=val

In [ ]:
frame2

In [ ]:
frame2["eastern"]=frame2["state"]=="Ohio"

In [ ]:
frame2

In [ ]:
del frame2["eastern"]

In [ ]:
frame2

In [ ]:
del frame2["oil"]

In [ ]:
frame2.index

In [ ]:
obj

In [ ]:
obj.index

In [ ]:
obj.index[0:3]

Immutability makes it safer to share Index objects among data structures.

In [ ]:
obj

In [ ]:
obj.index.name="Names"

In [ ]:
obj=DataFrame(obj)

In [ ]:
obj

In [ ]:
obj[0].name="Money"

In [ ]:
obj

In [ ]:
obj.index

In [ ]:
obj

In [ ]:
obj["Luck"]=[0,2,3,4]

In [ ]:
obj

In [ ]:
obj["car"]=np.arange(4)

In [ ]:
obj

In [ ]:
obj["car"]

In [ ]:
obj.rename(columns={"car":"Car"}, inplace=True)

In [ ]:
obj

In [ ]:
obj.columns.name="Attributes"

In [ ]:
obj

In [ ]:
obj.loc[len(obj)]={"Money": -3, "Luck":0, "Car":4}

In [ ]:
obj

In [ ]:
frame2

In [ ]:
frame2.rename(index={0:"blabla"})

In [ ]:
frame2.rename(columns={"state":"dudu"})

In [ ]:
frame2.name="dada"

In [ ]:
frame2.name

In [ ]:
frame2.columns.name="data"

In [ ]:
frame2

In [ ]:
frame2.index.name="time"

In [ ]:
frame2

## 5.2 Essential Functionality

We’ll focus on familiarizing you with heavily used features, leaving the less common (i.e., more esoteric) things for you to learn more about by reading the online pandas documentation

### Reindexing

In [ ]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])

In [ ]:
obj2=obj.reindex(["a","b","c","d","e"])

In [ ]:
obj2

You may want to do some interpolation or filling of values when reindexing. The method option allows us to do this, using a method such as `ffill`, which forward-fills **the values**:

In [ ]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])

In [ ]:
obj3

In [ ]:
obj4=obj3.reindex(index=np.arange(6), method="ffill")

### Dropping entries from an Axis

In [ ]:
obj4.drop(0)

With DataFrame, index values can be deleted from either axis

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=["Ohio", "Colorado", "Utah", "New York"], columns=["one", "two", "three", "four"])

In [ ]:
data

In [ ]:
data.drop(index=["Colorado", "Ohio"])

In [ ]:
data.drop(columns=["two"])

### Indexing, Selection, Filtering

You can either use the index or the position to extract a value from a series, but the position is ambiguous and not recommended (when using a single position it throws an error sometimes and it is better to use the `iloc` method)

In [ ]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj

In [ ]:
obj["b"]

In [ ]:
obj[1:3]

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=["Ohio", "Colorado", "Utah", "New York"], columns=["one", "two", "three", "four"])

In [ ]:
data

In [ ]:
data["one"]

In [ ]:
data[["three", "one"]]

In [ ]:
data[data["three"]>5]

In [ ]:
data<5

In [ ]:
data

In [ ]:
data.loc["Colorado"]

In [ ]:
data.loc[["Colorado", "New York"]]

In [ ]:
data.loc["Colorado", ["two", "three"]]

### Arithmetic and Data Alignment

pandas can make it much simpler to work with objects that have different indexes. For example, when you add objects, if any index pairs are not the same, the respective index in the result will be the union of the index pairs

In [ ]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=["a", "c", "e", "f", "g"])

In [ ]:
s1+s2

In the case of DataFrame, alignment is performed on both rows and columns:

In [ ]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"), index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"), index=["Utah", "Ohio", "Texas", "Oregon"])

In [ ]:
df1

In [ ]:
df2

In [ ]:
df1+df2

In [ ]:
df1.index

In [ ]:
df1.reindex(["Texas", "Ohio", "Colorado"])

In [ ]:
df1+df2

If you add DataFrame objects with no column or row labels in common, the result will contain all nulls. In arithmetic operations between differently indexed objects, you might want to fill with a special value, like 0, when an axis label is found in one object but not the other.

In [ ]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list("abcd"))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list("abcde"))

In [ ]:
df1+df2

In [ ]:
df1.add(df2, fill_value=0)

In [ ]:
df1.add(df2, fill_value=1000)

When reindexing a Series or DataFrame, you can also specify a different fill value:

In [ ]:
df1.reindex(columns=df2.columns, fill_value=0)

Arithmetic between DataFrame and Series is also defined. Let us consider an example using arrays

In [ ]:
arr = np.arange(12.).reshape((3, 4))

In [ ]:
arr-arr[0]

This is an example of **broadcasting**. By default, arithmetic between DataFrame and Series matches the index of the Series on the columns of the DataFrame, broadcasting down the rows:

In [ ]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"), index=["Utah", "Ohio", "Texas", "Oregon"])

In [ ]:
series = frame.iloc[0]

In [ ]:
frame

In [ ]:
series

In [ ]:
frame-series

In [ ]:
series2 = pd.Series(np.arange(3), index=["b", "e", "f"])

In [ ]:
frame+series2

If you want to instead broadcast over the columns, matching on the rows, you have to use one of the arithmetic methods and specify to match over the index.

In [ ]:
series3 = frame["d"]

In [ ]:
frame

In [ ]:
series3

In [ ]:
frame.sub(series3, axis="index")

### Function Application and Mapping

In [ ]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)), columns=list("bde"), index=["Utah", "Ohio", "Texas", "Oregon"])

In [ ]:
frame

In [ ]:
np.abs(frame)

Another frequent operation is applying a function on one-dimensional arrays to each column or row. DataFrame’s apply method does exactly this:

In [ ]:
def f1(x): 
    return x.max() - x.min()

In [ ]:
frame.apply(f1)

If you pass `axis="columns"` to apply, the function will be invoked once per row instead.

In [ ]:
frame.apply(f1, axis="columns")

The function passed to apply need not return a scalar value; it can also return a Series with multiple values:

In [ ]:
def f2(x): 
    return pd.Series([x.min(), x.max()], index=["min", "max"])

In [ ]:
frame.apply(f2)

In [ ]:
def my_format(x): 
    return f"{x:.2f}"

In [ ]:
fr2=frame.map(my_format)

In [ ]:
fr2["e"].dtype

### Sorting and Ranking

In [ ]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])

In [ ]:
obj.sort_index()

In [ ]:
obj.sort_values()

In [ ]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), index=["three", "one"], columns=["d", "a", "b", "c"])

In [ ]:
frame

In [ ]:
frame.sort_index()

In [ ]:
frame.sort_index(axis="columns", ascending=True) #default ascending=True

Any missing values are sorted to the end of the Series by default

In [ ]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [ ]:
obj.sort_values()

In [ ]:
obj.sort_values(na_position="first")

When sorting a DataFrame, you can use the data in one or more columns as the sort keys. To do so, pass one or more column names to sort_values:

In [ ]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})

In [ ]:
frame

In [ ]:
frame.sort_values("b")

In [ ]:
frame.sort_values(["a","b"])

**Ranking** assigns ranks from one through the number of valid data points in an array,  starting from the lowest value. The rank methods for Series and DataFrame are the place to look; by default, rank breaks ties by assigning each group the mean rank:

In [ ]:
obj = pd.Series([7, -5, 7, 4, 1000, 0, 4,-1])

In [ ]:
obj.rank()

In [ ]:
obj.rank(method="first")

In [ ]:
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1], "c": [-2, 5, 8, -2.5]})

In [ ]:
frame

In [ ]:
frame.rank(axis="columns")

### Axis Indexes with Duplicate Labels

In [ ]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])

In [ ]:
obj

In [ ]:
obj.index.is_unique

In [ ]:
obj["a"]

The same logic extends to indexing rows (or columns) in a DataFrame

In [ ]:
df = pd.DataFrame(np.random.standard_normal((5, 3)), index=["a", "a", "b", "b", "c"])

In [ ]:
df

In [ ]:
df.loc["b"]

In [ ]:
df.loc["c"]

## 5.3 Summarizing and Computing Descriptive Statistics

pandas objects are equipped with a set of common mathematical and statistical methods that extract a single value (like the sum or mean) from a Series, or a Series of values from the rows or columns of a DataFrame. They have built-in handling for missing data. Consider a small DataFrame:

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index=["a", "b", "c", "d"], columns=["one", "two"])

In [ ]:
df

In [ ]:
df.sum()

In [ ]:
df.sum(axis='columns')

When an entire row or column contains all NA values, the sum is 0, whereas if any value is not NA, then the result is NA. This can be disabled with the skipna option.

In [ ]:
df.sum(skipna=False)

In [ ]:
df.sum(axis='columns',skipna=False)

In [ ]:
df.mean(axis='columns')

In [ ]:
df

In [ ]:
df.idxmax()

In [ ]:
df.cumsum()

In [ ]:
df.describe()

In [ ]:
df

In [ ]:
obj = pd.Series(["a", "a", "b", "c"] * 4)

In [ ]:
obj.describe()

In [ ]:
obj

### Correlation and Covariance

This is just needed to make the older dataset work with our new version of pandas

In [ ]:
import sys
import pandas as pd

import pandas.core.indexes as core_indexes
import pandas.core.indexes.datetimes as dt_indexes

sys.modules["pandas.indexes"] = core_indexes
sys.modules["pandas.tseries.index"] = dt_indexes

In [ ]:
price = pd.read_pickle("~/Learning_Python/yahoo_price.pkl")
volume = pd.read_pickle("~/Learning_Python/yahoo_volume.pkl")

In [ ]:
price.head()

In [ ]:
volume.head()

I now compute percent changes of the prices

In [ ]:
returns = price.pct_change()

In [ ]:
returns.head()

An then we can start investigating whether there are any correlations among these returns! The corr method of Series computes the correlation of the overlapping, non-NA, aligned-by-index values in two Series. Relatedly, cov computes the covariance:

In [ ]:
np.nan in returns

In [ ]:
returns["MSFT"].corr(returns["IBM"])

In [ ]:
returns["MSFT"].cov(returns["IBM"])

In [ ]:
returns.corr()

In [ ]:
returns.cov()

In [ ]:
returns.corrwith(returns["IBM"])

Passing a DataFrame computes the correlations of matching column names.

In [ ]:
returns.corrwith(volume)

### Unique Values, Value Counts, and Membership

Another class of related methods extracts information about the values contained in a one-dimensional Series.

In [ ]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])

In [ ]:
uniques = obj.unique()

In [ ]:
pd.Series(uniques)

In [ ]:
obj.value_counts()

In [ ]:
obj.value_counts(sort=False)

`isin` performs a vectorized set membership check and can be useful in filtering a  dataset down to a subset of values in a Series or column in a DataFrame:

In [ ]:
obj

In [ ]:
mask = obj.isin(["b","c"])

In [ ]:
mask

In [ ]:
obj[mask]

# 6 Data Loading, Storage, and File Formats

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("pydata-book-3rd-edition/examples/ex1.csv")

In [ ]:
df

If the file has no header and we load it naively, it can be interpreted in some weird ways

In [ ]:
pd.read_csv("pydata-book-3rd-edition/examples/ex2.csv")

Adding some options specifying the kind of format of the file restores the desired result

In [ ]:
pd.read_csv("pydata-book-3rd-edition/examples/ex2.csv", header=None)

In [ ]:
pd.read_csv("pydata-book-3rd-edition/examples/ex2.csv", names=["a", "b", "c", "d", "message"])

In [ ]:
pd.read_csv("pydata-book-3rd-edition/examples/ex2.csv", names=["a", "b", "c", "d", "message"], index_col='message')

You can also have hierarchical indexing

In [ ]:
parsed = pd.read_csv("pydata-book-3rd-edition/examples/csv_mindex.csv", index_col=["key1", "key2"])

In [ ]:
parsed

Another possible problem is that the delimiter between values may be spaces or some other character, in which case it is better to specify that, otherwise values may be put together in unexpected ways

In [ ]:
wrong=pd.read_csv('pydata-book-3rd-edition/examples/ex3.txt')

In [ ]:
wrong

In [ ]:
wrong.columns

In [ ]:
wrong.columns.__len__()

In [ ]:
result=pd.read_csv('pydata-book-3rd-edition/examples/ex3.txt', sep=r"\s+")

In [ ]:
result

In [ ]:
result.columns

There is along list of options to manipulate data when reading it from various formats, like skipping rows, handling not assigned values

In [ ]:
pd.read_csv('pydata-book-3rd-edition/examples/ex4.csv')

In [ ]:
pd.read_csv('pydata-book-3rd-edition/examples/ex4.csv',skiprows=[0,2,3])

In [ ]:
df1 = pd.read_csv('pydata-book-3rd-edition/examples/ex5.csv')

In [ ]:
df1

In [ ]:
df1.isna()

`pandas.read_csv` has a list of many default NA value representations, but these  defaults can be disabled with the keep_default_na option:

In [ ]:
result2 = pd.read_csv('pydata-book-3rd-edition/examples/ex5.csv', keep_default_na=False)

In [ ]:
result2

In [ ]:
result2.isna()

### Reading Text Files in Pieces

When processing very large files or figuring out the right set of arguments to correctly process a large file, you may want to read only a small piece of a file or iterate  through smaller chunks of the file. I was trying to set the number of displayed rwos to a higher number, but I got into trouble with some cached values.

In [4]:
result = pd.read_csv('pydata-book-3rd-edition/examples/ex6.csv')

In [5]:
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [18]:
pd.read_csv('pydata-book-3rd-edition/examples/ex6.csv', nrows=30)

         one       two     three      four key
0   0.467976 -0.038649 -0.295344 -1.824726   L
1  -0.358893  1.404453  0.704965 -0.200638   B
2  -0.501840  0.659254 -0.421691 -0.057688   G
3   0.204886  1.074134  1.388361 -0.982404   R
4   0.354628 -0.133116  0.283763 -0.837063   Q
..       ...       ...       ...       ...  ..
25  1.759879 -0.515666 -0.230481  1.362317   S
26  0.126266  0.309281  0.382820 -0.239199   L
27  1.334360 -0.100152 -0.840731 -0.643967   6
28 -0.737620  0.278087 -0.053235 -0.950972   J
29 -1.148486 -0.986292 -0.144963  0.124362   Y

[30 rows x 5 columns]

To read a file in pieces, specify a chunksize as a number of rows:

In [19]:
chunker = pd.read_csv('pydata-book-3rd-edition/examples/ex6.csv', chunksize=1000)

In [20]:
type(chunker)

pandas.io.parsers.readers.TextFileReader

In [21]:
tot = pd.Series([], dtype='int64') 
for piece in chunker:  
    tot = tot.add(piece["key"].value_counts(), fill_value=0) 
    
tot = tot.sort_values(ascending=False)

In [26]:
tot[4:14]

key
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
V    328.0
I    327.0
U    326.0
P    324.0
dtype: float64

In [ ]:
tot.__len__()

36

In [38]:
np.sort(tot.index)

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C',
       'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
       'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'], dtype=object)

### Writing Data to Text Format

In [39]:
data = pd.read_csv('pydata-book-3rd-edition/examples/ex5.csv')

In [40]:
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [41]:
data.to_csv('pydata-book-3rd-edition/examples/out.csv')

Other delimiters can be used, of course (writing to sys.stdout so it prints the text result to the console rather than a file):

In [42]:
import sys

In [43]:
data.to_csv(sys.stdout, sep="|")

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

In [44]:
data.to_csv(sys.stdout, na_rep="NULL")

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

In [45]:
data.to_csv(sys.stdout, index=False, header=False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

### Working with Other Delimited Formats

In [46]:
import csv

In [74]:
f = open('pydata-book-3rd-edition/examples/ex7.csv')

In [53]:
reader = csv.reader(f)

In [54]:
for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [55]:
f.close()

In [56]:
with open('pydata-book-3rd-edition/examples/ex7.csv') as f:
    lines = list(csv.reader(f))

In [57]:
header, values = lines [0], lines[1:]

In [68]:
data_dict = {h: v for h, v in zip(header, zip(*values))}

Notice the subtle asterisk inside zip to zip between different rows with the same column instead of same row different column

In [69]:
list(zip(values))

[(['1', '2', '3'],), (['1', '2', '3'],)]

In [70]:
list(zip(*values))

[('1', '1'), ('2', '2'), ('3', '3')]

In [71]:
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

CSV files come in many different flavors. To define a new format with a different delimiter, string quoting convention, or line terminator, we could define a simple subclass of csv.Dialect:

In [75]:
class my_dialect(csv.Dialect):  
    lineterminator = "\n" 
    delimiter = ";" 
    quotechar = '"' 
    quoting = csv.QUOTE_MINIMAL 
reader = csv.reader(f, dialect=my_dialect)

In [78]:
f.close()

For files with more complicated or fixed multicharacter delimiters, you will not be able to use the csv module. In those cases, you’ll have to do the line splitting and other cleanup using the string’s  split method or the regular expression method re.split. Thankfully, pandas.read_csv is capable of doing almost anything you need if you pass the necessary options, so you only rarely will have to parse files by hand.

### JSON Data

In [79]:
obj = """ {"name": "Wes", "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"], "pet": null, "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},  {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}] } """

In [80]:
import json

In [81]:
result = json.loads(obj)

In [82]:
result

{'name': 'Wes',
 'cities_lived': ['Akron', 'Nashville', 'New York', 'San Francisco'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 34, 'hobbies': ['guitars', 'soccer']},
  {'name': 'Katie', 'age': 42, 'hobbies': ['diving', 'art']}]}

In [84]:
type(result)

dict

In [85]:
type(obj)

str

In [87]:
asjson = json.dumps(result)

In [88]:
asjson

'{"name": "Wes", "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"], "pet": null, "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]}, {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]}'

In [89]:
type(asjson)

str

In [90]:
siblings = pd.DataFrame(result['siblings'], columns=['name', 'age'])

In [91]:
siblings

    name  age
0  Scott   34
1  Katie   42

In [92]:
data.to_json(sys.stdout)

{"something":{"0":"one","1":"two","2":"three"},"a":{"0":1,"1":5,"2":9},"b":{"0":2,"1":6,"2":10},"c":{"0":3.0,"1":null,"2":11.0},"d":{"0":4,"1":8,"2":12},"message":{"0":null,"1":"world","2":"foo"}}

In [93]:
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

### XML and HTML: Web Scraping

Python has many libraries for reading and writing data in the ubiquitous HTML and XML formats. Examples include lxml, Beautiful Soup, and html5lib. While lxml is comparatively much faster in general, the other libraries can better handle malformed HTML or XML files. pandas has a built-in function, pandas.read_html, which uses all of these libraries to automatically parse tables out of HTML files as DataFrame objects.

In [97]:
tables = pd.read_html("pydata-book-3rd-edition/examples/fdic_failed_bank_list.html")

In [98]:
len(tables)

1

In [101]:
type(tables)

list

In [102]:
failures = tables[0]

In [103]:
failures.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

In [104]:
failures['Closing Date']

0      September 23, 2016
1         August 19, 2016
2             May 6, 2016
3          April 29, 2016
4          March 11, 2016
              ...
542         July 27, 2001
543           May 3, 2001
544      February 2, 2001
545     December 14, 2000
546      October 13, 2000
Name: Closing Date, Length: 547, dtype: str

In [105]:
close_timestamps = pd.to_datetime(failures['Closing Date'])

Below I take an object `datetime` and then I use the attribute `dt.year` and count how many times that year appears, calculating how many banks failed in that year

In [108]:
close_timestamps.dt.year

0      2016
1      2016
2      2016
3      2016
4      2016
       ...
542    2001
543    2001
544    2001
545    2000
546    2000
Name: Closing Date, Length: 547, dtype: int32

In [106]:
close_timestamps.dt.year.value_counts()

Closing Date
2010    157
2009    140
2011     92
2012     51
2008     25
       ...
2004      4
2001      4
2007      3
2003      3
2000      2
Name: count, Length: 15, dtype: int64

### Parsing XML with lxml.objectify

XML is another common structured data format supporting hierarchical, nested data with metadata.

Earlier, I showed the pandas.read_html function, which uses either lxml or Beautiful Soup under the hood to parse data from HTML. XML and HTML are structurally similar, but XML is more general. Here, I will show an example of how to use lxml to parse data from a more general XML format.

In [1]:
import numpy as np
import pandas as pd

In [2]:
from lxml import objectify

In [3]:
path = 'pydata-book-3rd-edition/datasets/mta_perf/Performance_MNR.xml'

In [4]:
with open(path) as f:
    parsed = objectify.parse(f)

In [5]:
root = parsed.getroot()

`root.INDICATOR` returns a generator yielding each `<INDICATOR>` XML element. For  each record, we can populate a dictionary of tag names (like YTD_ACTUAL) to data values (excluding a few tags) by running the following code:

In [6]:
data = []

In [7]:
skip_fields = ["PARENT_SEQ", "INDICATOR_SEQ",  "DESIRED_CHANGE", "DECIMAL_PLACES"]

In [8]:
for element in root.INDICATOR:
    el_data = {}
    for child in element.getchildren():
        if child.tag in skip_fields:
            continue
    el_data[child.tag] = child.pyval
data.append(el_data)

In [9]:
perf = pd.DataFrame(data)

In [10]:
perf.head()

  MONTHLY_ACTUAL
0

Here we have an error, because this is not the output I was expecting, there is way to little data. For the moment, I will not investigate further, since the point of the book was just to show how much easier is to use the built-in pandas method.

In [25]:
perf

  MONTHLY_ACTUAL
0

In [11]:
perf2 = pd.read_xml(path)

In [12]:
perf2

,INDICATOR_SEQ,PARENT_SEQ,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,DESIRED_CHANGE,INDICATOR_UNIT,DECIMAL_PLACES,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,U,%,1,95.00,96.90,95.00,96.90
1,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,U,%,1,95.00,96.00,95.00,95.00
2,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,U,%,1,95.00,96.30,95.00,96.90
3,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,U,%,1,95.00,96.80,95.00,98.30
4,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,U,%,1,95.00,96.60,95.00,95.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
643,373889,NaN,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,2011,8,Service Indicators,M,U,%,1,97.00,NaN,97.00,NaN
644,373889,NaN,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,2011,9,Service Indicators,M,U,%,1,97.00,NaN,97.00,NaN
645,373889,NaN,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,2011,10,Service Indicators,M,U,%,1,97.00,NaN,97.00,NaN
646,373889,NaN,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,2011,11,Service Indicators,M,U,%,1,97.00,NaN,97.00,NaN
647,373889,NaN,Metro-North Railroad,Escalator Availability,Percent of the time that escalators are operat...,2011,12,Service Indicators,M,U,%,1,97.00,NaN,97.00,NaN

## 6.3 Interacting with Web APIs

Many websites have public APIs providing data feeds via JSON or some other format. There are a number of ways to access these APIs from Python; one method that I recommend is the requests package, which can be installed with pip or conda

## 6.4 Interacting with Databases  

In a business setting, a lot of data may not be stored in text or Excel files. SQL-based relational databases (such as SQL Server, PostgreSQL, and MySQL) are in wide use, and many alternative databases have become quite popular. The choice of database is usually dependent on the performance, data integrity, and scalability needs of an application. pandas has some functions to simplify loading the results of a SQL query into a DataFrame. As an example, I’ll create a SQLite3 database using Python’s built-in  sqlite3 driver:

# 7 Data Cleaning and Preparation

During the course of doing data analysis and modeling, a significant amount of time is spent on data preparation: loading, cleaning, transforming, and rearranging. Such tasks are often reported to take up 80% or more of an analyst’s time. Sometimes the way that data is stored in files or databases is not in the right format for a particular task. Many researchers choose to do ad hoc processing of data from one form to another using a general-purpose programming language, like Python, Perl, R, or Java, or Unix text-processing tools like sed or awk. Fortunately, pandas, along with the built-in Python language features, provides you with a high-level, flexible, and fast set of tools to enable you to manipulate data into the right form.

## 7.1 Handling Missing Data

In [13]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

In [14]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [15]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In pandas, we’ve adopted a convention used in the R programming language by referring to missing data as NA, which stands for not available. In statistics applications, NA data may either be data that does not exist or that exists but was not observed (through problems with data collection, for example). When cleaning up data for analysis, it is often important to do analysis on the missing data itself to identify data collection problems or potential biases in the data caused by missing data. 

**The built-in Python None value is also treated as NA:**

In [16]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])

In [17]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [18]:
float_data = pd.Series([1, 2, None], dtype='float64')

In [19]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

### Filtering Out Missing Data

There are a few ways to filter out missing data. While you always have the option to do it by hand using pandas.isna and Boolean indexing, dropna can be helpful. On a Series, it returns the Series with only the nonnull data and index values:

In [20]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [21]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [22]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [23]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [24]:
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [25]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

In [26]:
data.dropna(how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [27]:
data[4] = np.nan

In [28]:
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [29]:
data.dropna(axis='columns', how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

Suppose you want to keep only rows containing at most a certain number of missing observations. You can indicate this with the thresh argument:

In [30]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))

In [31]:
df.iloc[:4, 1] = np.nan

In [32]:
df.iloc[:2, 2] = np.nan

In [33]:
df

          0         1         2
0 -0.740594       NaN       NaN
1  0.117080       NaN       NaN
2  0.191262       NaN -2.053206
3  0.103987       NaN -1.041921
4  0.911682  1.269977 -0.161852
5 -1.503037  0.228657  0.331760
6 -1.493274 -0.282856 -0.343640

In [35]:
df.dropna()

          0         1         2
4  0.911682  1.269977 -0.161852
5 -1.503037  0.228657  0.331760
6 -1.493274 -0.282856 -0.343640

In [36]:
df.dropna(thresh=2)

          0         1         2
2  0.191262       NaN -2.053206
3  0.103987       NaN -1.041921
4  0.911682  1.269977 -0.161852
5 -1.503037  0.228657  0.331760
6 -1.493274 -0.282856 -0.343640

### Filling In Missing Data  

Rather than filtering out missing data (and potentially discarding other data along with it), you may want to fill in the “holes” in any number of ways. For most purposes, the fillna method is the workhorse function to use. Calling fillna with a constant replaces missing values with that value:

In [37]:
df.fillna(0)

          0         1         2
0 -0.740594  0.000000  0.000000
1  0.117080  0.000000  0.000000
2  0.191262  0.000000 -2.053206
3  0.103987  0.000000 -1.041921
4  0.911682  1.269977 -0.161852
5 -1.503037  0.228657  0.331760
6 -1.493274 -0.282856 -0.343640

In [38]:
df.fillna({1: 0.5, 2: 0})

          0         1         2
0 -0.740594  0.500000  0.000000
1  0.117080  0.500000  0.000000
2  0.191262  0.500000 -2.053206
3  0.103987  0.500000 -1.041921
4  0.911682  1.269977 -0.161852
5 -1.503037  0.228657  0.331760
6 -1.493274 -0.282856 -0.343640

The same interpolation methods available for reindexing (see Table 5-3) can be used with fillna:

In [39]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan

In [40]:
df

          0         1         2
0  1.095154  0.762090 -0.707966
1 -0.524658 -1.083593 -1.223348
2 -0.275638       NaN -1.734319
3 -1.355145       NaN  0.523587
4  0.664165       NaN       NaN
5 -0.821756       NaN       NaN

In [43]:
df.ffill()

          0         1         2
0  1.095154  0.762090 -0.707966
1 -0.524658 -1.083593 -1.223348
2 -0.275638 -1.083593 -1.734319
3 -1.355145 -1.083593  0.523587
4  0.664165 -1.083593  0.523587
5 -0.821756 -1.083593  0.523587

In [44]:
df.ffill(limit=2)

          0         1         2
0  1.095154  0.762090 -0.707966
1 -0.524658 -1.083593 -1.223348
2 -0.275638 -1.083593 -1.734319
3 -1.355145 -1.083593  0.523587
4  0.664165       NaN  0.523587
5 -0.821756       NaN  0.523587

In [45]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])

In [47]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## 7.2 Data Transformation  

So far in this chapter we’ve been concerned with handling missing data. Filtering, cleaning, and other transformations are another class of important operations.

In [48]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"], "k2": [1, 1, 2, 3, 3, 4, 4]})

In [49]:
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [51]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [53]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [54]:
data["v1"] = range(7)

In [55]:
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [56]:
data.drop_duplicates(subset=["k1"])

    k1  k2  v1
0  one   1   0
1  two   1   1

In [57]:
data.drop_duplicates(["k1", "k2"], keep="last")

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### Transforming Data Using a Function or Mapping

For many datasets, you may wish to perform some transformation based on the values in an array, Series, or column in a DataFrame. Consider the following hypothetical data collected about various kinds of meat:

In [111]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon", "pastrami", "corned beef", "bacon","pastrami", "honey ham", "nova lox"], "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [112]:
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [114]:
data.loc[data['food']=='bacon','ounces']

0     4.0
2    12.0
5     8.0
Name: ounces, dtype: float64

Suppose you wanted to add a column indicating the type of animal that each food came from. Let’s write down a mapping of each distinct meat type to the kind of animal:

In [63]:
meat_to_animal = { "bacon": "pig", "pulled pork": "pig", "pastrami": "cow", "corned beef": "cow", "honey ham": "pig", "nova lox": "salmon" }

The map method on a Series accepts a function or dictionary-like object containing a mapping to do the transformation of values:

In [64]:
data["animal"] = data["food"].map(meat_to_animal)

In [70]:
def get_animal(x): 
    return meat_to_animal[x]

In [71]:
data['food'].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: str

### Replacing Values

In [120]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [121]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [122]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [119]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [123]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [124]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Renaming Axis Indexes

In [125]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)), index=["Ohio", "Colorado", "New York"], columns=["one", "two", "three", "four"])

In [126]:
def transform(x):
    return x[:4].upper()

In [127]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='str')

In [128]:
data.index = data.index.map(transform)

In [129]:
data

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [130]:
data.rename(index=str.title, columns=str.upper)

      ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [131]:
data

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [132]:
data.rename(index={"OHIO": "INDIANA"}, columns={"three": "peekaboo"})

         one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11